# Generated by Django 6.0.4 on 2026-04-22 09:25

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short_name', models.CharField(choices=[('private_workspace', 'Private Workspace'), ('view_team_workspace', 'View Team Workspace'), ('view_assigned_cases', 'View Assigned Cases'), ('view_all_cases', 'View All Cases'), ('view_closed_cases', 'View Closed Cases'), ('manage_cases', 'Manage Cases'), ('own_diary', 'Own Diary'), ('view_team_diary', 'View Team Diary'), ('manage_all_diaries', 'Manage All Diaries'), ('view_client_updates', 'View Client Updates'), ('send_client_updates', 'Send Client Updates'), ('view_repository', 'View Repository'), ('add_to_repository', 'Add to Repository'), ('manage_repository', 'Manage Repository'), ('view_own_billing', 'View Own Billing'), ('manage_billing', 'Manage Billing'), ('full_billing_access', 'Full Billing Access'), ('use_ai', 'Use AI Component'), ('train_ai', 'Train AI / Upload Documents'), ('admin_ai', 'Admin AI Settings'), ('view_users', 'View Users'), ('manage_users', 'Manage Users'), ('full_user_management', 'Full User Management'), ('view_digital_repository', 'View Digital Repository'), ('manage_digital_repository', 'Manage Digital Repository')], max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'permission',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short_name', models.CharField(choices=[('managing_partner', 'Managing Partner'), ('senior_partner', 'Senior Partner'), ('junior_partner', 'Junior Partner'), ('senior_associate', 'Senior Associate'), ('associate', 'Associate'), ('junior_associate', 'Junior Associate'), ('trainee', 'Trainee Advocate / Pupil'), ('founding_partner', 'Founding Partner'), ('partner', 'Partner'), ('junior_advocate', 'Junior Advocate'), ('pupil', 'Pupil / Trainee Advocate'), ('admin', 'System Admin')], max_length=100, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('firm_type', models.CharField(choices=[('big_law', 'Big Law Firm'), ('mid_size', 'Mid-Sized Firm'), ('system', 'System')], default='big_law', max_length=20)),
                ('access_level', models.IntegerField(default=1, help_text='Numeric rank: higher = more access. e.g Managing Partner=10, Trainee=1')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'role',
                'ordering': ['-access_level'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in E.164 format', regex='^\\+?\\d{9,15}$')])),
                ('id_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('firm_type', models.CharField(choices=[('big_law', 'Big Law Firm'), ('mid_size', 'Mid-Sized Firm')], default='big_law', help_text='Determines which role hierarchy applies', max_length=20)),
                ('status', models.IntegerField(default=0)),
                ('is_mfa', models.IntegerField(default=0)),
                ('is_activated', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='authentication_users', to='auth.group', verbose_name='groups')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_users', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='authentication_users', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ManyToManyField(blank=True, related_name='users', to='authentication.role')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ActivationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token_used', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activation_token',
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='admin_photos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_profile',
            },
        ),
        migrations.CreateModel(
            name='AdvocateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_number', models.CharField(blank=True, help_text='LSK admission / practice number', max_length=50, null=True)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('specialization', models.CharField(blank=True, help_text='e.g. Conveyancing, Litigation, Family Law', max_length=200, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='advocate_photos/')),
                ('bio', models.TextField(blank=True, max_length=1000, null=True)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='advocate_ids/')),
                ('date_of_admission', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advocate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'advocate_profile',
            },
        ),
        migrations.CreateModel(
            name='LoginOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=10)),
                ('used', models.IntegerField(default=0)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('expiry_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'login_otp',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token_used', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_reset_token',
            },
        ),
        migrations.CreateModel(
            name='PrivateWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partition', models.CharField(choices=[('notes', 'Notes'), ('drafts', 'Drafts'), ('pleadings', 'Pleadings'), ('affidavits', 'Affidavits'), ('applications', 'Applications'), ('conveyancing', 'Conveyancing'), ('agreements', 'Agreements')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='workspace/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'private_workspace',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='authentication.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='authentication.role')),
            ],
            options={
                'db_table': 'role_permission',
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
