# Generated by Django 6.0.4 on 2026-04-28 12:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('firm_type', models.CharField(choices=[('big_law', 'Big Law Firm'), ('mid_size', 'Mid-Sized Firm')], default='big_law', max_length=20)),
                ('email', models.EmailField(help_text='Primary contact email for the firm', max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='firm_logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_firm', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'firm',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='firm',
            field=models.ForeignKey(blank=True, help_text='Null = system-level default role', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='authentication.firm'),
        ),
        migrations.AddField(
            model_name='user',
            name='firm',
            field=models.ForeignKey(blank=True, help_text='Null only for super admins', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='authentication.firm'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('firm', 'short_name')},
        ),
        migrations.CreateModel(
            name='FirmInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='authentication.firm')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.role')),
            ],
            options={
                'db_table': 'firm_invite',
            },
        ),
    ]
